# Generated by Django 4.0.2 on 2022-03-01 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_customer_mobile_alter_customer_phone'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='is_signed',
            new_name='status',
        ),
        migrations.AddField(
            model_name='contract',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_due',
            field=models.DateField(auto_now_add=True, default='2000-05-23'),
            preserve_default=False,
        ),
    ]
