# Generated by Django 4.0.2 on 2022-03-01 09:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=24, verbose_name='fname')),
                ('last_name', models.CharField(max_length=24, verbose_name='lname')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='email')),
                ('phone', models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^(?:\\+33\\s|0)[1-9](?:\\s\\d{2}){4}$')], verbose_name='phone')),
                ('mobile', models.IntegerField(validators=[django.core.validators.RegexValidator('^(?:\\+33\\s|0)[1-9](?:\\s\\d{2}){4}$')], verbose_name='mobile')),
                ('company_name', models.CharField(max_length=64, verbose_name='company_name')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('sales_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='sales_contact')),
            ],
        ),
    ]
