# Generated by Django 4.0.2 on 2022-03-01 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_sales_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^(?:\\+33\\s|0)[1-9](?:\\d{2}){4}$')], verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^(?:\\+33\\s|0)[1-9](?:\\d{2}){4}$')], verbose_name='phone'),
        ),
    ]
