# Generated by Django 4.0.2 on 2022-03-01 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_mobile_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^(\\d{2}){5}$')], verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^(\\d{2}){5}$')], verbose_name='phone'),
        ),
    ]
