# Generated by Django 4.0.2 on 2022-03-01 10:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_status', models.BooleanField(default=False)),
                ('commentary', models.TextField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(validators=[django.core.validators.RegexValidator('^(0?[1-9]|[12][0-9]|3[01])[\\/\\-](0?[1-9]|1[012])[\\/\\-]\\d{4}$')], verbose_name='eventdate')),
                ('number_guests', models.IntegerField(blank=True, null=True)),
                ('commentary', models.TextField(max_length=256)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('contract_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractevent', to='contract.contract')),
                ('event_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventstatus', to='event.status')),
                ('support_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportcontact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
